const minutesEl = document.querySelector("minutes")
const secondsEl = document.querySelector("seconds")
const millisecondsEl = document.querySelector("minutes")
const startBtn = document.querySelector("startBtn")
const pauseBtn = document.querySelector("pauseBtn")
const resumeBtn = document.querySelector("resumeBtn")
const resetBtn = document.querySelector("resetBtn")
